### ISSUE TITLE
`Force old-style SSL` in Adium

### ISSUE THREAD

**Issue by farski** [robn/nginx#2]
(This may actually be a FastMail question)

For connecting to my FastMail XMPP in Adium (1.5.10), I've always had to use the `Force old-style SSL` option, otherwise I'd get a `Connection reset by peer` error. Should this nginx change allow connections without that?

**Comment by robn** [comment]
No, its unrelated.

"Old-style SSL" is for the SSL-before-XMPP mode of operation on port 5223. We (FastMail) recommend it because we argue its more secure than the "standard" XMPP STARTTLS method, but not everyone agrees.

You can uncheck "old-style SSL" if you change the port to 5222. I would advise not doing that though, especially if what you have works :)

(I actually just yesterday updated our XMPP setup docs to include that setting because it does trip a few people up!)
