### ISSUE TITLE
TCP Proxy

### ISSUE THREAD

**Issue by dapriett** [robn/nginx#3]
Hello,

I was looking at how to proxy and load balance multiple XMPP servers and I came across this project, as well as a [TCP Proxy module](https://github.com/yaoweibin/nginx_tcp_proxy_module).  I was wondering if you looked at that module, and if it does that same thing?  Could the nginx xmpp proxy stuff be broken out into a module as well?

Thanks!

**Comment by robn** [comment]
I hadn't seen the TCP proxy module, but it looks rather like an early version of the stream module that recent versions of nginx have.

It doesn't do quite the same thing. Ultimately everything in nginx results in a proxied TCP stream. Its what happens during the setup that is interesting. You need some basic understanding of the protocol, particularly the authentication, and then the ability to select a backend server and start proxying. In this way the XMPP support is identical in concept to nginx's IMAP, POP3 and SMTP support.

The reason its in the mail module and not standalone is that there's a lot of useful services provided by the mail module that I don't want to have to duplicate. As I said, its nearly identical to the existing mail protocol support. It can't be done as a submodule to the mail module in the same way that the http module can have submodules because the mail module simply has no support for that.
